import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Locale, i18n } from "@/../i18n.config";
import Providers from "@/components/wrappers/Providers";
import Navbar from "@/components/layout/navbar/Navbar";
import { cn } from "@/lib/utils";
import CircleAnimation from "@/components/animations/CircleAnimation";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["800", "400", "100", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "K A P H I",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}
export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html
      lang={params.lang}
      className="h-full"
      dir={params.lang === "en" ? "ltr" : "rtl"}
    >
      <body className="relative h-full   antialiased">
        <main
          className={cn(
            `relative flex flex-col min-h-screen`,
            { "font-poppins": params.lang === "en" },
            { "font-beINNormal": params.lang === "ar" },
            poppins.variable
          )}
        >
          <Providers attribute="class" defaultTheme="dark">
            <Navbar lang={params.lang} />
            <div className="flex-grow flex-1">
              <CircleAnimation />
              {children}
            </div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
